# Generated by Django 4.1.7 on 2023-04-01 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('Cordenador', models.CharField(max_length=255)),
                ('data_incricao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('num_casa', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgm', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.curso')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.endereco')),
            ],
        ),
    ]
