# Generated by Django 4.1.7 on 2023-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='num_casa',
            field=models.IntegerField(),
        ),
    ]
